title: Automated Threat Intelligence Integration
description: A complete breakdown on the integration of MISP with Sentinal through a VM
show_downloads: false
google_analytics:
theme: jekyll-theme-midnight
